export const TILE_TYPES = {
  START: "START",
  SAFE: "SAFE",
  INCOME: "INCOME",
  TAX: "TAX",
  REWARD: "REWARD",
  PENALTY: "PENALTY",
  SURPRISE: "SURPRISE",
} as const;

export type TileType = (typeof TILE_TYPES)[keyof typeof TILE_TYPES];

export const DICE_TRACK: TileType[] = [
  "START",
  "SAFE",
  "INCOME",
  "TAX",
  "SURPRISE",
  "PENALTY",
  "REWARD",
  "SAFE",
  "INCOME",
  "TAX",
  "SURPRISE",
  "SAFE",
  "PENALTY",
  "INCOME",
  "SAFE",
  "REWARD",
  "TAX",
  "SURPRISE",
  "SAFE",
  "TAX",
  "REWARD",
  "SAFE",
  "INCOME",
  "PENALTY",
  "SURPRISE",
  "SAFE",
  "TAX",
  "INCOME",
  "SAFE",
  "REWARD",
  "PENALTY",
  "SURPRISE",
  "SAFE",
  "PENALTY",
] as const;
