import type { MapConfig } from "../schema/mapConfig";

export const SAMPLE_MAP_CONFIG: MapConfig = {
  id: "sample-subcontinent",
  name: "Sample Subcontinent",
  version: "0.1.0",
  grid: {
    orientation: "pointy",
    hexSize: 12,
    origin: { q: -3, r: -4 },
    bounds: { minQ: -3, maxQ: 6, minR: -4, maxR: 5 },
    resolutionTag: "prototype",
  },
  hexes: [
    { q: -1, r: -1, s: 2, stateId: "aurora" },
    { q: 0, r: -1, s: 1, stateId: "aurora" },
    { q: 1, r: -1, s: 0, stateId: "aurora" },
    { q: 1, r: 0, s: -1, stateId: "borealis" },
    { q: 2, r: 0, s: -2, stateId: "borealis" },
    { q: 2, r: 1, s: -3, stateId: "borealis" },
    { q: 0, r: 1, s: -1, stateId: "cerulea" },
    { q: 1, r: 1, s: -2, stateId: "cerulea" },
    { q: 0, r: 2, s: -2, stateId: "cerulea" },
    { q: -2, r: 0, s: 2, stateId: "dorado" },
    { q: -2, r: 1, s: 1, stateId: "dorado" },
    { q: -1, r: 1, s: 0, stateId: "dorado" },
    { q: 3, r: -1, s: -2, stateId: "ember" },
    { q: 3, r: 0, s: -3, stateId: "ember" },
    { q: 4, r: -1, s: -3, stateId: "ember" },
    { q: -1, r: 2, s: -1, stateId: "fjord" },
    { q: -1, r: 3, s: -2, stateId: "fjord" },
    { q: 0, r: 3, s: -3, stateId: "fjord" },
    { q: 5, r: 0, s: -5, stateId: null },
    { q: 5, r: 1, s: -6, stateId: null },
  ],
  territories: [
    {
      id: "aurora",
      name: "Aurora",
      displayColor: "#f39c12",
      hexes: ["-1,-1", "0,-1", "1,-1"],
    },
    {
      id: "borealis",
      name: "Borealis",
      displayColor: "#3498db",
      hexes: ["1,0", "2,0", "2,1"],
    },
    {
      id: "cerulea",
      name: "Cerulea",
      displayColor: "#1abc9c",
      hexes: ["0,1", "1,1", "0,2"],
    },
    {
      id: "dorado",
      name: "Dorado",
      displayColor: "#9b59b6",
      hexes: ["-2,0", "-2,1", "-1,1"],
    },
    {
      id: "ember",
      name: "Ember",
      displayColor: "#e74c3c",
      hexes: ["3,-1", "3,0", "4,-1"],
    },
    {
      id: "fjord",
      name: "Fjord",
      displayColor: "#2ecc71",
      hexes: ["-1,2", "-1,3", "0,3"],
    },
  ],
  adjacencies: {
    aurora: ["borealis", "cerulea", "dorado"],
    borealis: ["aurora", "cerulea", "ember"],
    cerulea: ["aurora", "borealis", "fjord"],
    dorado: ["aurora", "fjord"],
    ember: ["borealis"],
    fjord: ["cerulea", "dorado"],
  },
};
